name: 03 runner

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    runner-03:
        runs-on: ubuntu-latest
        steps:
            - name: ¿Quien soy?
              run: 
                whoami
            - name: ¿Donde estoy?
              run: 
                pwd
            - name: ¿Qué archivos hay?
              run: 
                dir
            - name: mensaje personal
              run: 
                echo "Hola, soy el runner"
